### ISSUE TITLE
db error?

### ISSUE THREAD

**Issue by pclausen94** [VORPCORE/VORP_txAdmin#18]
When clicking "run recipe", I get the following error:
Task Failed: Can't create table vorpcore_f5e949.whitelist (errno: 150 "Foreign key constraint is incorrectly formed") Options: { "action": "query_database", "file": "./temp/vorp_txAdminRecipe/MariaDB.sql" } Debug/Status: ["5.2.0","Windows 10","loading task query_database"]

**Comment by domx4q** [comment]
I also have a Database error (on creation), but mine is a bit different.:
```
[txAdmin:Deployer] Task Failed: BLOB/TEXT column 'items' can't have a default value
Options:
{
  "action": "query_database",
  "file": "./temp/vorp_txAdminRecipe/MariaDB.sql"
}
Debug/Status: ["5.2.0","Linux 4.15.0","loading task query_database"]
```

**Comment by AndrewR3K** [comment]
> I also have a Database error (on creation), but mine is a bit different.:
> 
> ```
> [txAdmin:Deployer] Task Failed: BLOB/TEXT column 'items' can't have a default value
> Options:
> {
>   "action": "query_database",
>   "file": "./temp/vorp_txAdminRecipe/MariaDB.sql"
> }
> Debug/Status: ["5.2.0","Linux 4.15.0","loading task query_database"]
> ```
please ensure you have maria db installed.

**Comment by AndrewR3K** [comment]
> When clicking "run recipe", I get the following error:
> Task Failed: Can't create table vorpcore_f5e949.whitelist (errno: 150 "Foreign key constraint is incorrectly formed") Options: { "action": "query_database", "file": "./temp/vorp_txAdminRecipe/MariaDB.sql" } Debug/Status: ["5.2.0","Windows 10","loading task query_database"]

I will look into this today.

**Comment by domx4q** [comment]
> > I also have a Database error (on creation), but mine is a bit different.:
> > ```
> > [txAdmin:Deployer] Task Failed: BLOB/TEXT column 'items' can't have a default value
> > Options:
> > {
> >   "action": "query_database",
> >   "file": "./temp/vorp_txAdminRecipe/MariaDB.sql"
> > }
> > Debug/Status: ["5.2.0","Linux 4.15.0","loading task query_database"]
> > ```
> 
> please ensure you have maria db installed.

I have MariaDB installed. On the first time I hadn't, but then I watched the linked YouTube Video and did it, to avoid conflicts with existing Files I completeley reinstalled it, but than the error occured multiple times.
I had some problems with making MariaDB accesible over the Internet, because I run the FXServer on a V-Server and not local. But now The DB works (also tested with DataGrip).

Does the DB Version might be the Issue? I installed the latest Stable (10.11.2)

I can also ensure, that the DB connection is working, beacuse when I pass wrong credentials, It says wrong credentials.

**Comment by zWyzzzzz** [comment]
any news?

**Comment by AndrewR3K** [comment]
I tested this today with latest mariadb and it installed perfectly fine.

are you using latest mariadb install? (Not mysql)

**Comment by zWyzzzzz** [comment]
yes the last one

**Comment by jeann2013** [comment]
The solution is change this   `vorpv2`.`users`  for  `users` in the file **txAdminRecipe\txData\Vorpcore_FB481B.base\temp\vorp_txAdminRecipe\MariaDB.sql**
![Screenshot 2023-02-26 062327](https://user-images.githubusercontent.com/3299025/221407595-473c9631-8edf-4cde-986f-bcb9d4687e63.png)

**Comment by AndrewR3K** [comment]
Good catch! I totally missed that. I’ll update soon

**Comment by lebss44** [comment]
![image](https://user-images.githubusercontent.com/126419167/221433723-4db15978-4f9d-48b7-9c81-8b9adde8a244.png)
we cant start server , there is probleme in CORE ( me and 2 other membres)

**Comment by AndrewR3K** [comment]
> ![image](https://user-images.githubusercontent.com/126419167/221433723-4db15978-4f9d-48b7-9c81-8b9adde8a244.png)
> we cant start server , there is probleme in CORE ( me and 2 other membres)

This is the wrong place to post this issue. Please post in vorp core repo, or you can join our discord more faster support.

**Comment by lebss44** [comment]
i post a message any personne answer me , me and 2 other peaple

**Comment by AndrewR3K** [comment]
> i post a message any personne answer me , me and 2 other peaple

Please read my prior message.
