### ISSUE TITLE
Error loading script server/server.lua in resource vorp_admin: attempt to yield from outside a coroutine

### ISSUE THREAD

**Issue by draobrehtom** [VORPCORE/VORP_txAdmin#23]
```
Error loading script server/server.lua in resource vorp_admin: attempt to yield from outside a coroutine
stack traceback:
	[C]: in function 'coroutine.yield'
	citizen:/scripting/lua/scheduler.lua:113: in field 'Await'
	citizen:/scripting/lua/scheduler.lua:741: in field 'addItem'
	@vorp_admin/server/server.lua:19: in main chunk	
```
![image](https://github.com/VORPCORE/VORP_txAdmin/assets/6503721/90024bb7-38c7-4362-b517-249f7e895430)

![image](https://github.com/VORPCORE/VORP_txAdmin/assets/6503721/ccf62a90-ba6e-4857-9cc5-7d251b8a6eac)

**Comment by outsider31000** [comment]
![image](https://github.com/VORPCORE/VORP_txAdmin/assets/87246847/8d9b1b6a-7894-444e-8143-023a43a53a88)
 how are you reporting errors when you dont even update your scripts ?

**Comment by draobrehtom** [comment]
@outsider31000 Lol, I just installed vorp with the help of this tx recipe and got the error. Update txRecipe

**Comment by outsider31000** [comment]
![image](https://github.com/VORPCORE/VORP_txAdmin/assets/87246847/a8e8aea1-f93a-4b98-8114-f6b6d906560f)
 it tells you to update the script  in case you are blind

**Comment by draobrehtom** [comment]
You should update txAdmin recipe! In case you can't read from a first time

**Comment by outsider31000** [comment]
learn how to read

**Comment by draobrehtom** [comment]
By the way, it is not written in server console to update inventory

**Comment by draobrehtom** [comment]
> learn how to read

Learn your manners young man

**Comment by outsider31000** [comment]
then it means you dont need to update... its common sense

**Comment by draobrehtom** [comment]
You are not able to work with feedbacks

**Comment by draobrehtom** [comment]
> then it means you dont need to update... its common sense

If I don't update (update only vorp_admin), I still  receive error

**Comment by outsider31000** [comment]
what feedbacks ?  you have issues becaue you cant read, and come here to tell me to update a tx recepie implying it my fault?

**Comment by draobrehtom** [comment]
> what feedbacks ? you have issues becaue you cant read, and come here to tell me to update a tx recepie implying it my fault?

I don't have issue man, I don't give a sheet about it, I just tell you there error - it's my feedback about installation of framework with txAdmin.

**Comment by outsider31000** [comment]
you telling me theres an error when you cant follow what it says "to update" ?  you dont need to tell me anything, there are no error and no issues if people follow what it says.

**Comment by draobrehtom** [comment]
Yes, there an error in txRecipe/vorp_pre-made, just accept the fact

**Comment by outsider31000** [comment]
update the script error is gone simple as that follow what it says.

**Comment by draobrehtom** [comment]
I did it and it works. And you  some day will update vorp_pre-made and recipe.yml, some day...

**Comment by outsider31000** [comment]
premade is updated when the scipt is deemed fully functional until then it in tests. it seems you dont know anything about development.

**Comment by draobrehtom** [comment]
> premade is updated when the scipt is deemed fully functional until then it in tests. it seems you dont know anything about development.

But it is good that you know everything about it! Stop being so egoist, learn how to work with community or find someone. 

Ah yeah, you just kicked/banned me from Vorp discord. This tells everything is need to know about you :)

**Comment by outsider31000** [comment]
you tought cause you behind a keyboard you can say anything you want without consequences? next time learn how to respect to those who are making content for you to use for free.

**Comment by outsider31000** [comment]
if you think im gonna me making content for people like you to come and tell me what to do cause they ignorante? you wrong.

**Comment by draobrehtom** [comment]
> next time learn how to respect to those who are making content for you to use for free.

Me: posting issue on github, in mind to help
You: calling me blind

All right, all right ;)

**Comment by outsider31000** [comment]
there was no issue if you read what it say i called you blind when yyou told me what to do

**Comment by outsider31000** [comment]
my energy is always matched
