### ISSUE TITLE
MySQL Causing problem in table items

### ISSUE THREAD

**Issue by cl3i550n** [VORPCORE/VORP_txAdmin#26]
- Coluns BLOB, TEXT, GEOMETRY or JSON in the case not have default values '{}' in MySQL.

Possible solution

Option 1
```sql
`metadata` LONGTEXT NULL DEFAULT NULL COLLATE 'utf8mb4_bin',
```

Option 2
```sql
`metadata` LONGTEXT NOT NULL DEFAULT '{}' COLLATE 'utf8mb4_bin',
```

![image](https://github.com/VORPCORE/VORP_txAdmin/assets/80117221/2daf9f66-f66c-4a04-a539-5f0b18cf104f)

**Comment by outsider31000** [comment]
The solution is for you to update mariaDB version

**Comment by outsider31000** [comment]
That only happens on lower versions.
